{% set version = "4.0.0" %}

package:
  name: azure
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/azure/azure-{{ version }}.zip
  sha256: 7d6afa332fccffe1a9390bcfac5122317eec657c6029f144d794603a81cd0e50

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - python
    - azure-mgmt >=4.0
    - azure-servicebus >=0.21.1
    - azure-storage-blob >=1.3
    - azure-storage-queue >=1.3
    - azure-storage-file >=1.3
    - azure-servicemanagement-legacy >=0.20.6

test:
  imports:
    - azure
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'Microsoft Azure Client Libraries for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
    - carlodri
    - scopatz
